image: ghcr.io/traversaro/gitpod-ubuntu-20.04:latest
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
- port: 5900
  onOpen: ignore 
- port: 35900
  onOpen: ignore
- port: 6942
  onOpen: ignore
workspaceLocation: "."
tasks:
- command: start-vnc-session.sh
- command: android.sh
- command: chrome.sh
- command: gp await-port 6080 && gp preview $(gp url 6080)

